### ISSUE TITLE
Could not find Fragment constructor com.klarna.checkout.a

### ISSUE THREAD

**Issue by kitek** [klarna/kco-mobile-sdk#28]
Version: 'com.klarna.checkout:sdk:1.6.8'
Platform: Android

How to reproduce:

1. Enable "Do not keep activies" in Developer options
2. On checkout screen move App to the background
3. Restore app from the background

Stacktrace:
```
Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.klarna.checkout.a: could not find Fragment constructor
    at android.app.Fragment.instantiate(Fragment.java:550)
    at android.app.FragmentContainer.instantiate(FragmentContainer.java:53)
    at android.app.FragmentState.instantiate(FragmentState.java:77)
    at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:2862)
    at android.app.FragmentController.restoreAllState(FragmentController.java:140)
    at android.app.Activity.onCreate(Activity.java:1044)
    at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:75)
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:335)
    at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
Caused by: java.lang.NoSuchMethodException: <init> []
    at java.lang.Class.getConstructor0(Class.java:2327)
    at java.lang.Class.getConstructor(Class.java:1725)
    at android.app.Fragment.instantiate(Fragment.java:531)
    at android.app.FragmentContainer.instantiate(FragmentContainer.java:53) 
    at android.app.FragmentState.instantiate(FragmentState.java:77) 
    at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:2862) 
    at android.app.FragmentController.restoreAllState(FragmentController.java:140) 
    at android.app.Activity.onCreate(Activity.java:1044) 
    at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:75) 
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:335) 
    at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:85) 
```

**Comment by omarbh** [comment]
Hi @kitek big thanks for reporting this issue. We will look into it and we will release a fix for it soon 👍

**Comment by patrikfigura** [comment]
@kitek Hey, issue should be fixed in `1.6.10` release (if you are using support library use `1.6.10-support`). Let me know if it fixed your problem

**Comment by kitek** [comment]
@patrikfigura It seems to be working fine. Thanks!

**Comment by rifqimfahmi** [comment]
Hi @patrikfigura can you tell us how you fix this in the code? I also encounter this crash in my project but can't find any solution on the internet. Thank you

**Comment by Shaftar** [comment]
Hi did any one get  this fixed. Please can you share your solution? Which library should i update?
