### ISSUE TITLE
After exiting checkout activity, any new checkout renders blank

### ISSUE THREAD

**Issue by adrianblancode** [klarna/kco-mobile-sdk#32]
We have a checkout flow which integrates the Klarna Checkout SDK, where when the user confirms the checkout they get sent to a new activity where we display the Klarna checkout (Native).

The problem arises when the user exits the Klarna checkout activity, reenters our checkout, confirms it again, gets a new token and starts the Klarna checkout activity again. After two or three of these, the Klarna checkout will not render at all. It seems that the WebView layouts with zero height.

After this bug occurs, it seems like any additional attempts will also not render correctly.

Platform: Android
Device: Samsung S10, Android 9
Sdk version: 1.6.10-support
Sdk integration: Native

**Comment by omarbh** [comment]
Hi! thanks for Hi @adrianblp! thanks for reporting this. We will look into it and get back to you asap

**Comment by adrianpalmquist** [comment]
@adrianblp Do you call [`checkout.destroy()`](https://github.com/klarna/kco-mobile-sdk/blob/master/android/README.md#cleanup) when the user exits the Klarna checkout activity and then re-initialize it when the user re-enters the Klarna checkout activity?

**Comment by adrianblancode** [comment]
@adrianpalmquist Yes. We init KlarnaCheckout and add it to our ScrollView in onCreate, and we call destroy() in onDestroy().

The only thing which I can think of we are doing differently from the documentation is that we don't have a launchMode set for our klarna checkout activity in our manifest since android studio complains about on "singleTask|singleTop". Not sure if that would matter anyway since we always have to close that activity to get anywhere else in the app.

**Comment by adrianpalmquist** [comment]
@adrianblp We are not able to reproduce it in our testing environment. Can you please share a screen recording and relevant logs.

**Comment by adrianblancode** [comment]
This is from entering the klarna checkout activity (fully functional), exiting it and then entering it again with a new snippet (does not show).

I have a screen capture of it, but GitHub doesn't accept video files so I can mail it to you (or just message it to me at adrian.blanco@bontouch.com) if it's a more private email

```2019-06-20 12:00:13.033 12469-12484/se.nansen.coop.at.debug I/n.coop.at.debu: Background concurrent copying GC freed 183401(8MB) AllocSpace objects, 40(4MB) LOS objects, 50% free, 20MB/40MB, paused 234us total 127.724ms
2019-06-20 12:00:14.085 12469-12469/se.nansen.coop.at.debug W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@ab152e1
2019-06-20 12:00:14.093 12469-12469/se.nansen.coop.at.debug I/DecorView: createDecorCaptionView >> DecorView@81f3063[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
2019-06-20 12:00:14.104 12469-12469/se.nansen.coop.at.debug D/ScrollView: initGoToTop
2019-06-20 12:00:14.104 12469-12469/se.nansen.coop.at.debug D/ScrollView: initGoToTop
2019-06-20 12:00:14.137 12469-12469/se.nansen.coop.at.debug I/WebViewFactory: Loading com.android.chrome version 75.0.3770.101 (code 377010137)
2019-06-20 12:00:14.184 12469-12469/se.nansen.coop.at.debug I/cr_LibraryLoader: Time to load native libraries: 5 ms (timestamps 264-269)
2019-06-20 12:00:14.198 12469-12469/se.nansen.coop.at.debug I/chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
2019-06-20 12:00:14.198 12469-12469/se.nansen.coop.at.debug I/cr_LibraryLoader: Expected native library version number "75.0.3770.101", actual native library version number "75.0.3770.101"
2019-06-20 12:00:14.205 12469-14032/se.nansen.coop.at.debug W/cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
2019-06-20 12:00:14.206 12469-14032/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
2019-06-20 12:00:14.209 12469-12469/se.nansen.coop.at.debug I/cr_BrowserStartup: Initializing chromium process, singleProcess=false
2019-06-20 12:00:14.264 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: requestNetwork; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:14.266 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: requestNetwork; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:14.291 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
2019-06-20 12:00:14.291 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
2019-06-20 12:00:14.292 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2019-06-20 12:00:14.292 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2019-06-20 12:00:14.292 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2019-06-20 12:00:14.292 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2019-06-20 12:00:14.292 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2019-06-20 12:00:14.292 12469-12469/se.nansen.coop.at.debug W/n.coop.at.debu: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
2019-06-20 12:00:14.308 12469-12469/se.nansen.coop.at.debug D/Dialog: mIsSamsungBasicInteraction = false
2019-06-20 12:00:14.308 12469-12469/se.nansen.coop.at.debug D/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2019-06-20 12:00:14.310 12469-12469/se.nansen.coop.at.debug I/DecorView: createDecorCaptionView >> DecorView@2090120[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
2019-06-20 12:00:14.326 12469-12595/se.nansen.coop.at.debug W/FlurryAgent: Flurry session resumed for context:se.nansen.coop.feature.checkout.klarnacheckoutpayment.KlarnaCheckoutPaymentActivity@71dfcf4
2019-06-20 12:00:14.341 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel constructed: fd=245
2019-06-20 12:00:14.343 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: setView = DecorView@81f3063[KlarnaCheckoutPaymentActivity] TM=true MM=false
2019-06-20 12:00:14.350 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: requestNetwork; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:14.353 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: requestNetwork; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:14.364 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2019-06-20 12:00:14.365 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@ec51876[OccCheckoutActivity]
2019-06-20 12:00:14.365 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:14.378 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: dispatchAttachedToWindow
2019-06-20 12:00:14.394 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: Relayout returned: old=[0,0][1080,2280] new=[0,0][1080,2280] result=0x7 surface={valid=true 529337647104} changed=true
2019-06-20 12:00:14.406 12469-12801/se.nansen.coop.at.debug D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2019-06-20 12:00:14.406 12469-12801/se.nansen.coop.at.debug D/OpenGLRenderer: eglCreateWindowSurface = 0x7b5cee3380, 0x7b3efb8010
2019-06-20 12:00:14.407 12469-12469/se.nansen.coop.at.debug D/ScrollView:  onsize change changed 
2019-06-20 12:00:14.435 12469-14054/se.nansen.coop.at.debug W/cr_media: Requires BLUETOOTH permission
2019-06-20 12:00:14.466 12469-14070/se.nansen.coop.at.debug W/AudioCapabilities: Unsupported mime audio/ac4
2019-06-20 12:00:14.466 12469-14070/se.nansen.coop.at.debug W/AudioCapabilities: Unsupported mime audio/x-ima
2019-06-20 12:00:14.471 12469-14070/se.nansen.coop.at.debug W/AudioCapabilities: Unsupported mime audio/x-ape
2019-06-20 12:00:14.474 12469-14070/se.nansen.coop.at.debug W/AudioCapabilities: Unsupported mime audio/eac3-joc
2019-06-20 12:00:14.486 12469-14070/se.nansen.coop.at.debug W/AudioCapabilities: Unsupported mime audio/mpeg-L1
2019-06-20 12:00:14.486 12469-14070/se.nansen.coop.at.debug W/AudioCapabilities: Unsupported mime audio/mpeg-L2
2019-06-20 12:00:14.489 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2019-06-20 12:00:14.493 12469-14070/se.nansen.coop.at.debug W/AudioCapabilities: Unsupported mime audio/x-ms-wma
2019-06-20 12:00:14.513 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@81f3063[KlarnaCheckoutPaymentActivity]
2019-06-20 12:00:14.513 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:14.513 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unrecognized profile 8192 for video/hevc
2019-06-20 12:00:14.513 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@81f3063[KlarnaCheckoutPaymentActivity]
2019-06-20 12:00:14.514 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:14.514 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: startInputInner - Id : 0
2019-06-20 12:00:14.514 12469-12469/se.nansen.coop.at.debug I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-06-20 12:00:14.516 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel constructed: fd=266
2019-06-20 12:00:14.516 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel destroyed: fd=201
2019-06-20 12:00:14.517 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unrecognized profile 8192 for video/hevc
2019-06-20 12:00:14.519 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unrecognized profile 4 for video/hevc
2019-06-20 12:00:14.522 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unsupported mime video/mp43
2019-06-20 12:00:14.525 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
2019-06-20 12:00:14.525 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
2019-06-20 12:00:14.525 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
2019-06-20 12:00:14.526 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unsupported mime video/wvc1
2019-06-20 12:00:14.527 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unsupported mime video/wvc1
2019-06-20 12:00:14.539 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
2019-06-20 12:00:14.540 12469-14070/se.nansen.coop.at.debug W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
2019-06-20 12:00:14.553 12469-14070/se.nansen.coop.at.debug I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2019-06-20 12:00:14.558 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1080, 2280) ci=Rect(0, 112 - 0, 126) vi=Rect(0, 112 - 0, 126) or=1
2019-06-20 12:00:14.814 12469-12801/se.nansen.coop.at.debug W/libEGL: EGLNativeWindowType 0x7b3e52a010 disconnect failed
2019-06-20 12:00:14.814 12469-12801/se.nansen.coop.at.debug D/OpenGLRenderer: eglDestroySurface = 0x7b3e82d600, 0x7b3e52a000
2019-06-20 12:00:14.839 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: Relayout returned: old=[0,0][1080,2280] new=[0,0][1080,2280] result=0x5 surface={valid=false 0} changed=true
2019-06-20 12:00:14.840 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: setWindowStopped(true) old=false
2019-06-20 12:00:14.866 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: Surface release. android.view.WindowManagerGlobal.setStoppedState:669 android.app.Activity.performStop:7647 android.app.ActivityThread.callActivityOnStop:4372 android.app.ActivityThread.performStopActivityInner:4350 android.app.ActivityThread.handleStopActivity:4425 android.app.servertransaction.StopActivityItem.execute:41 android.app.servertransaction.TransactionExecutor.executeLifecycleState:145 android.app.servertransaction.TransactionExecutor.execute:70 
2019-06-20 12:00:14.869 12469-12595/se.nansen.coop.at.debug W/FlurryAgent: Flurry session paused for context:se.nansen.coop.feature.checkout.occcheckout.OccCheckoutActivity@c700dd9
2019-06-20 12:00:18.224 12469-12469/se.nansen.coop.at.debug I/chromium: [INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: https://checkout-eu.klarna.com/190619-3f8a5b8/checkout-template.html[REDACTED]
2019-06-20 12:00:22.114 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: ViewPostIme pointer 0
2019-06-20 12:00:22.439 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: ViewPostIme pointer 1
2019-06-20 12:00:22.470 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: setWindowStopped(false) old=true
2019-06-20 12:00:22.471 12469-12595/se.nansen.coop.at.debug W/FlurryAgent: Flurry session resumed for context:se.nansen.coop.feature.checkout.occcheckout.OccCheckoutActivity@c700dd9
2019-06-20 12:00:22.476 12469-12469/se.nansen.coop.at.debug W/FlurryAgent: Event count incremented: CHECKOUT_FLOW
2019-06-20 12:00:22.482 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: setWindowStopped(false) old=false
2019-06-20 12:00:22.491 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2019-06-20 12:00:22.491 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@81f3063[KlarnaCheckoutPaymentActivity]
2019-06-20 12:00:22.491 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:22.514 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: Relayout returned: old=[0,0][1080,2280] new=[0,0][1080,2280] result=0x7 surface={valid=true 528199307264} changed=true
2019-06-20 12:00:22.518 12469-12801/se.nansen.coop.at.debug D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2019-06-20 12:00:22.518 12469-12801/se.nansen.coop.at.debug D/OpenGLRenderer: eglCreateWindowSurface = 0x7b1ff59e80, 0x7afb21d010
2019-06-20 12:00:22.534 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2019-06-20 12:00:22.569 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@ec51876[OccCheckoutActivity]
2019-06-20 12:00:22.569 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:22.572 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@ec51876[OccCheckoutActivity]
2019-06-20 12:00:22.572 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:22.572 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: startInputInner - Id : 0
2019-06-20 12:00:22.573 12469-12469/se.nansen.coop.at.debug I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-06-20 12:00:22.573 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel constructed: fd=302
2019-06-20 12:00:22.573 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel destroyed: fd=266
2019-06-20 12:00:22.882 12469-12801/se.nansen.coop.at.debug W/libEGL: EGLNativeWindowType 0x7b3efb8010 disconnect failed
2019-06-20 12:00:22.882 12469-12801/se.nansen.coop.at.debug D/OpenGLRenderer: eglDestroySurface = 0x7b5cee3380, 0x7b3efb8000
2019-06-20 12:00:22.894 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: Relayout returned: old=[0,0][1080,2280] new=[0,0][1080,2280] result=0x5 surface={valid=false 0} changed=true
2019-06-20 12:00:22.897 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: setWindowStopped(true) old=false
2019-06-20 12:00:22.897 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: Surface release. android.view.WindowManagerGlobal.setStoppedState:669 android.app.Activity.performStop:7647 android.app.ActivityThread.callActivityOnStop:4372 android.app.ActivityThread.performStopActivityInner:4350 android.app.ActivityThread.handleStopActivity:4425 android.app.servertransaction.TransactionExecutor.performLifecycleSequence:192 android.app.servertransaction.TransactionExecutor.cycleToPath:165 android.app.servertransaction.TransactionExecutor.executeLifecycleState:142 
2019-06-20 12:00:22.898 12469-12595/se.nansen.coop.at.debug W/FlurryAgent: Flurry session paused for context:se.nansen.coop.feature.checkout.klarnacheckoutpayment.KlarnaCheckoutPaymentActivity@71dfcf4
2019-06-20 12:00:22.921 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: dispatchDetachedFromWindow
2019-06-20 12:00:22.922 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@6fbfbe4[KlarnaCheckoutPaymentActivity]: Surface release. android.view.ViewRootImpl.doDie:7944 android.view.ViewRootImpl.die:7912 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.ActivityThread.handleDestroyActivity:4747 android.app.servertransaction.DestroyActivityItem.execute:39 android.app.servertransaction.TransactionExecutor.executeLifecycleState:145 
2019-06-20 12:00:22.926 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel destroyed: fd=245
2019-06-20 12:00:22.934 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: unregisterNetworkCallback; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:22.935 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: unregisterNetworkCallback; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:22.944 12469-12469/se.nansen.coop.at.debug W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:356)
        at org.chromium.android_webview.AwContents.a(PG:330)
        at org.chromium.android_webview.AwContents.a(PG:684)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:288)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at a.b.a.c.f.run(MessageSender.java:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2019-06-20 12:00:24.098 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: ViewPostIme pointer 0
2019-06-20 12:00:24.249 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: ViewPostIme pointer 1
2019-06-20 12:00:28.027 12469-12673/se.nansen.coop.at.debug I/n.coop.at.debu: Explicit concurrent copying GC freed 291448(14MB) AllocSpace objects, 34(868KB) LOS objects, 49% free, 15MB/31MB, paused 52us total 76.420ms
2019-06-20 12:00:29.537 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: ViewPostIme pointer 0
2019-06-20 12:00:29.560 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: ViewPostIme pointer 1
2019-06-20 12:00:34.172 12469-12469/se.nansen.coop.at.debug W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@fa53a4f
2019-06-20 12:00:34.179 12469-12469/se.nansen.coop.at.debug I/DecorView: createDecorCaptionView >> DecorView@11eb3c8[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
2019-06-20 12:00:34.193 12469-12469/se.nansen.coop.at.debug D/ScrollView: initGoToTop
2019-06-20 12:00:34.193 12469-12469/se.nansen.coop.at.debug D/ScrollView: initGoToTop
2019-06-20 12:00:34.210 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: requestNetwork; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:34.213 12469-12469/se.nansen.coop.at.debug D/ConnectivityManager: requestNetwork; CallingUid : 10360, CallingPid : 12469
2019-06-20 12:00:34.222 12469-12469/se.nansen.coop.at.debug D/Dialog: mIsSamsungBasicInteraction = false
2019-06-20 12:00:34.223 12469-12469/se.nansen.coop.at.debug D/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2019-06-20 12:00:34.225 12469-12469/se.nansen.coop.at.debug I/DecorView: createDecorCaptionView >> DecorView@a01c9b3[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
2019-06-20 12:00:34.236 12469-12595/se.nansen.coop.at.debug W/FlurryAgent: Flurry session resumed for context:se.nansen.coop.feature.checkout.klarnacheckoutpayment.KlarnaCheckoutPaymentActivity@7b286e5
2019-06-20 12:00:34.245 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel constructed: fd=201
2019-06-20 12:00:34.246 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@7ef007[KlarnaCheckoutPaymentActivity]: setView = DecorView@11eb3c8[KlarnaCheckoutPaymentActivity] TM=true MM=false
2019-06-20 12:00:34.247 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2019-06-20 12:00:34.247 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@ec51876[OccCheckoutActivity]
2019-06-20 12:00:34.247 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:34.258 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@7ef007[KlarnaCheckoutPaymentActivity]: dispatchAttachedToWindow
2019-06-20 12:00:34.273 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@7ef007[KlarnaCheckoutPaymentActivity]: Relayout returned: old=[0,0][1080,2280] new=[0,0][1080,2280] result=0x7 surface={valid=true 529337491456} changed=true
2019-06-20 12:00:34.279 12469-12801/se.nansen.coop.at.debug D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2019-06-20 12:00:34.279 12469-12801/se.nansen.coop.at.debug D/OpenGLRenderer: eglCreateWindowSurface = 0x7b4d0cc500, 0x7b3ef92010
2019-06-20 12:00:34.280 12469-12469/se.nansen.coop.at.debug D/ScrollView:  onsize change changed 
2019-06-20 12:00:34.309 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@7ef007[KlarnaCheckoutPaymentActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2019-06-20 12:00:34.344 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@11eb3c8[KlarnaCheckoutPaymentActivity]
2019-06-20 12:00:34.345 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:34.346 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: prepareNavigationBarInfo() DecorView@11eb3c8[KlarnaCheckoutPaymentActivity]
2019-06-20 12:00:34.346 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: getNavigationBarColor() -1
2019-06-20 12:00:34.346 12469-12469/se.nansen.coop.at.debug D/InputMethodManager: startInputInner - Id : 0
2019-06-20 12:00:34.346 12469-12469/se.nansen.coop.at.debug I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-06-20 12:00:34.348 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel constructed: fd=273
2019-06-20 12:00:34.348 12469-12469/se.nansen.coop.at.debug D/InputTransport: Input channel destroyed: fd=302
2019-06-20 12:00:34.358 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@7ef007[KlarnaCheckoutPaymentActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1080, 2280) ci=Rect(0, 112 - 0, 126) vi=Rect(0, 112 - 0, 126) or=1
2019-06-20 12:00:34.649 12469-12801/se.nansen.coop.at.debug W/libEGL: EGLNativeWindowType 0x7afb21d010 disconnect failed
2019-06-20 12:00:34.650 12469-12801/se.nansen.coop.at.debug D/OpenGLRenderer: eglDestroySurface = 0x7b1ff59e80, 0x7afb21d000
2019-06-20 12:00:34.659 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: Relayout returned: old=[0,0][1080,2280] new=[0,0][1080,2280] result=0x5 surface={valid=false 0} changed=true
2019-06-20 12:00:34.659 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: setWindowStopped(true) old=false
2019-06-20 12:00:34.659 12469-12469/se.nansen.coop.at.debug D/ViewRootImpl@eb1270c[OccCheckoutActivity]: Surface release. android.view.WindowManagerGlobal.setStoppedState:669 android.app.Activity.performStop:7647 android.app.ActivityThread.callActivityOnStop:4372 android.app.ActivityThread.performStopActivityInner:4350 android.app.ActivityThread.handleStopActivity:4425 android.app.servertransaction.StopActivityItem.execute:41 android.app.servertransaction.TransactionExecutor.executeLifecycleState:145 android.app.servertransaction.TransactionExecutor.execute:70 
2019-06-20 12:00:34.661 12469-12595/se.nansen.coop.at.debug W/FlurryAgent: Flurry session paused for context:se.nansen.coop.feature.checkout.occcheckout.OccCheckoutActivity@c700dd9
```

**Comment by adrianblancode** [comment]
A band aid fix that was discovered was to disable caching on the WebView

```
(klarnaCheckout.view as? WebView)?.settings
            ?.apply {
                setAppCacheEnabled(false)
                cacheMode = WebSettings.LOAD_NO_CACHE
            }
```

**Comment by adrianpalmquist** [comment]
Placing the checkout view in a `ScrollView` is recommended instead. Please note that disabling web view cache is not recommended as this will impact performance on subsequent loads.
