### ISSUE TITLE
Application getting CRASH....

### ISSUE THREAD

**Issue by roycep93** [klarna/kco-mobile-sdk#36]
Application getting crash.

i use **implementation 'com.klarna.checkout:sdk:1.6.11'** Latest version.

Can you please UPLOAD proper sample with SAMEPLE All code with checkout url..

How i can generate checkoutURL?

currently i use https://api.playground.klarna.com/checkout/v3/orders/ 
use for **html_snippet**  can you please add sample with backend and app code.

2019-11-06 11:45:14.141 8932-8932/com.shop.rm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shop.rm, PID: 8932
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at a.b.a.d.a.a(CheckoutController.java:5)
        at com.klarna.checkout.KlarnaCheckout.setSnippet(KlarnaCheckout.java:1)
        at com.shop.rm.payment.PaymentKlarnaWebActivity.createKCOfromSnippet(PaymentKlarnaWebActivity.java:78)
        at com.shop.rm.payment.PaymentKlarnaWebActivity.getCheckoutFromUrl(PaymentKlarnaWebActivity.java:64)
        at com.shop.rm.payment.PaymentKlarnaWebActivity.initKlarnaCheckout(PaymentKlarnaWebActivity.java:52)
        at com.shop.rm.payment.PaymentKlarnaWebActivity.onCreate(PaymentKlarnaWebActivity.java:35)
        at android.app.Activity.performCreate(Activity.java:7802)

**Comment by adrianpalmquist** [comment]
Hi @roycep93, can you provide the html_snippet?

**Comment by omarbh** [comment]
Hi @roycep93 I will close this ticket as we did not get an answer from you.
